version: 2
formats: all
python:
    version: 3
    install:
        - requirements: docs/requirements.txt
        - method: pip
          path: .
sphinx:
    configuration: docs/conf.py
    fail_on_warning: true
