import re

PLAIN_DIRECTIVES = {
    '%': (None, FieldType('%', None)),
    'a': ('remote_ip', ip_address),   ### useragent_ip?
    'A': ('local_ip', ip_address),
    'B': ('response_size', integer),
    'b': ('response_size', clf(integer)),
    'D': ('microseconds', integer),
    'f': ('filename', esc_string),
    'h': ('remote_host', esc_string),
    'H': ('protocol', clf(esc_string)),
    'k': ('keepalive', integer),
    'l': ('ident', clf(esc_string)),
        ### Rethink name; remote_logname? ident_logname? ident_user?
    'm': ('method', clf(esc_string)),
    'p': ('port', integer),
    'P': ('pid', integer),
    'q': ('query', esc_string),
    'r': ('request', clf(esc_string)),
    'R': ('handler', esc_string),
    's': ('status', clf(integer)),
    't': ('time', ### Apache timestamp ),
    'T': ('seconds', integer),
    'u': ('remote_user', clf(esc_string)),  ### "auth_user"?
        ### XXX: A user with an empty name is represented by '""' (two
        ### double-quotes)
    'U': ('path', clf(esc_string)),
    'v': ('server_name', esc_string),
    'V': ('canonical_server_name', esc_string),  ### Rethink name
    'X': ('connection_status', FieldType('[-+X]', str)),
    'I': ('bytes_received', integer),  ### Format: apr_off_t_toa
    'O': ('bytes_sent', integer),      ### Format: apr_off_t_toa
    'S': ('bytes_combined', integer),  ### Format: apr_off_t_toa
    '^FB': ???

    'L': ???  ### Error log only?
}

PARAMETERIZED_DIRECTIVES = {
    'a': {
        'c': ('underlying_peer_ip', ip_address),  ### Rethink name; client_ip?
    },
    'C': ('cookie', ???),
    'e': ('envvar', esc_string),
    'i': ('request_header', clf(esc_string)),
    'n': ('note', esc_string),
    'o': ('response_header', esc_string),
    'p': {
        'canonical': ('canonical_port', integer),
        'local': ('local_port', integer),
        'remote': ('remote_port', integer),
    },
    'P': {
        'pid': ('pid', integer),
        'tid': ('tid', integer),  ### apr_psprintf "%pT" format
        'hextid': ('hextid', ???),
            ### apr_psprintf "%pt" or "%pT" format
            # (May be decimal if generated by older APR)
    },
    't': ('time', ??? ),
    'T': {
        'ms': ('milliseconds', integer),
        'us': ('microseconds', integer),
        's': ('seconds', integer),
    },
    '^ti': ('request_trailer_line', esc_string),
    '^to': ('response_trailer_line', esc_string),
}

def format2regex(fmt, plain_directives=None, parameterized_directives=None):
    if plain_directives is None:
        plain_directives = PLAIN_DIRECTIVES
    if parameterized_directives is None:
        parameterized_directives = PARAMETERIZED_DIRECTIVES
    groups = []
    rgx = ''
    for m in re.finditer(r'''
        % (?:!?\d+(?:,\d+)*)? (?:\{(?P<param>.*?)\})? (?P<directive>\^..|.)
        | (?P<literal>.)
    ''', fmt, flags=re.X):
        if m.group('literal') is not None:
            if m.group('literal') == '%':
                raise InvalidFormatError(fmt)
            rgx += re.escape(m.group('literal'))
            continue
        elif m.group('param') is not None:
            spec = parameterized_directives[m.group('directive')]
            param = m.group('param')
            if isinstance(spec, dict):
                name = (spec[param][0],)
                dtype = spec[param][1]
            else:
                name = (spec[0], param)
                dtype = spec[1]
        else:
            name, dtype = plain_directives[m.group('directive')]
        if name is None:
            rgx += dtype.regex
        else:
            groups.append((name, m.group(0)))
            rgx += r'({})'.format(dtype.regex)
    return (groups, re.compile(rgx))
