# http://httpd.apache.org/docs/current/mod/mod_log_config.html

FORMAT_DIRECTIVES = {
    ### TODO: Change the human names to match those used in the Apache source
    '%': (None, FieldType('%', None)),
    'a': ('remote_ip', ip_address),   ### useragent_ip?
    '{*}a': {
        'c': ('underlying_peer_ip', ip_address),  ### Rethink name; client_ip?
    },
    'A': ('local_ip', ip_address),
    'B': ('response_size', integer),
    'b': ('response_size', clf(integer)),
    '{*}C': ('cookie_*', ???),
    'D': ('microseconds', integer),
    '{*}e': ('envvar_*', esc_string),
    'f': ('filename', esc_string),
    'h': ('remote_host', esc_string),
    'H': ('protocol', clf(esc_string)),
    '{*}i': ('request_header_*', clf(esc_string)),
    'k': ('keepalive', integer),
    'l': ('ident', clf(esc_string)), ### Rethink name; remote_logname? ident_logname? ident_user?
    'm': ('method', clf(esc_string)),
    '{*}n': ('note_*', esc_string),
    '{*}o': ('response_header_*', esc_string),
    'p': ('port', integer),
    '{*}p': {
        'canonical': ('canonical_port', integer),
        'local': ('local_port', integer),
        'remote': ('remote_port', integer),
    },
    'P': ('pid', integer),
    '{*}P': {
        'pid': ('pid', integer),
        'tid': ('tid', integer),  ### apr_psprintf "%pT" format
        'hextid': ('hextid', ???),
            ### apr_psprintf "%pt" or "%pT" format
            # (May be decimal if generated by older APR)
    },
    'q': ('query', esc_string),
    'r': ('request', clf(esc_string)),
    'R': ('handler', esc_string),
    's': ('status', clf(integer)),
    't': ('time', ### Apache timestamp ),
    '{*}t': ???
    'T': ('seconds', integer),
    '{*}T': {
        'ms': ('milliseconds', integer),
        'us': ('microseconds', integer),
        's': ('seconds', integer),
    },
    'u': ('remote_user', clf(esc_string)),  ### "auth_user"?
        ### XXX: A user with an empty name is represented by '""' (two
        ### double-quotes)
    'U': ('path', clf(esc_string)),
    'v': ('server_name', esc_string),
    'V': ('canonical_server_name', esc_string),  ### Rethink name
    'X': ('connection_status', FieldType('[-+X]', str)),
    'I': ('bytes_received', integer),  ### Format: apr_off_t_toa
    'O': ('bytes_sent', integer),      ### Format: apr_off_t_toa
    'S': ('bytes_combined', integer),  ### Format: apr_off_t_toa
    '^FB': ???
    '{*}^ti': ('request_trailer_line_*', esc_string),
    '{*}^to': ('response_trailer_line_*', esc_string),

    'L': ???  ### Error log only?
}
